version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1608
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - ingesoft_db:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1608
    ports:
      - "8080:8080"

volumes:
  ingesoft_db:
  ingesoft_bucket:
